# Generated by Django 5.1.6 on 2025-03-04 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import date


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_at_alter_task_due_date_alter_task_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=date.today),
            preserve_default=False,
        ),
    ]
